CREATE TABLE "integration_setting" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"smtp_host" text,
	"smtp_port" integer,
	"smtp_secure" boolean,
	"smtp_user" text,
	"smtp_pass_encrypted" text,
	"email_from" text,
	"email_webhook_secret_encrypted" text,
	"google_client_id" text,
	"google_client_secret_encrypted" text,
	"zoom_client_id" text,
	"zoom_client_secret_encrypted" text,
	"storage_driver" text,
	"s3_endpoint" text,
	"s3_region" text,
	"s3_bucket" text,
	"s3_access_key_id" text,
	"s3_secret_access_key_encrypted" text,
	"r2_bucket" text,
	"r2_account_id" text,
	"r2_access_key_id" text,
	"r2_secret_access_key_encrypted" text,
	"storage_public_base_url" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
